# Generated by Django 4.2.3 on 2023-08-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('najot', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doktor',
            options={},
        ),
        migrations.RenameField(
            model_name='price',
            old_name='doc',
            new_name='price_doc',
        ),
    ]
