# Generated by Django 4.2.3 on 2023-08-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('najot', '0002_price_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
